package br.com.fiap.fintech.model.bean;

public enum CategoriaDeGasto {

	ALUGUEL,
	CONDOMINIO,
	MERCADO,
	COMBUSTIVEL,
	MEDICAMENTOS,
	PLANO_DE_CELULAR,
	INTERNET,
	SERVICO_DE_STREAMING,
	SEGURO_RESIDENCIAL,
	SEGURO_AUTO;
}
